#!/usr/bin/env python3
"""Generate src/modules/ggml_opencl_loader.c: the OpenCL functions ggml-opencl
calls, forwarded to the device's libOpenCL.so, opened at runtime.

ggml-opencl calls OpenCL directly. Linking libOpenCL.so would keep the app
from starting on devices without it, and the NDK has no OpenCL anyway, so
Android builds compile ggml-opencl into liboriel.so with these definitions
instead (like src/modules/ggml_vulkan_loader.c for Vulkan on Windows).

Usage: scripts/android/gen-opencl-loader.py <ggml/src/ggml-opencl> <OpenCL-Headers> > src/modules/ggml_opencl_loader.c
Rerun it when llama.cpp is updated (the build fails on a missing function).
"""
import re
import sys

src_dir, headers = sys.argv[1], sys.argv[2]
used = set()
for f in ("ggml-opencl.cpp", "cl-program-cache.cpp"):
    used |= set(re.findall(r"\b(cl[A-Z][A-Za-z0-9]+)\s*\(", open(f"{src_dir}/{f}").read()))
text = open(f"{headers}/CL/cl.h").read() + open(f"{headers}/CL/cl_ext.h").read()


def split_params(p):
    out, depth, cur = [], 0, ""
    for ch in p:
        if ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += ch
    if cur.strip():
        out.append(cur)
    return [" ".join(re.sub(r"/\*.*?\*/", "", x, flags=re.S).split()) for x in out]


def param_name(p):
    fn = re.search(r"\(\s*CL_CALLBACK\s*\*\s*(\w+)\s*\)", p)
    if fn:
        return fn.group(1)
    return re.findall(r"(\w+)\s*(?:\[\s*\d*\s*\])?\s*$", p)[0]


funcs = []
for name in sorted(used):
    m = re.search(r"extern CL_API_ENTRY\s+([^;]*?)\s*CL_API_CALL\s+" + name + r"\s*\(([^;]*?)\)\s*CL_API_SUFFIX", text, re.S)
    if not m:
        sys.exit(f"{name}: no prototype in the OpenCL headers")
    ret = " ".join(m.group(1).replace("CL_API_PREFIX__VERSION_1_2_DEPRECATED", "").split())
    params = split_params(m.group(2))
    if params == ["void"]:
        params = []
    funcs.append((name, ret, params))

print("""// Generated by scripts/android/gen-opencl-loader.py: do not edit.
//
// Android, -Dggml_opencl: ggml-opencl is compiled into liboriel.so and calls
// these OpenCL functions, which forward to the device's libOpenCL.so (Adreno
// and Mali drivers ship one; the NDK doesn't), opened on first use. Without
// it oriel_opencl_loader_available() is 0 and ggml_gpu.zig never registers
// the OpenCL backend, so the forwarders never run without a target.

#define CL_TARGET_OPENCL_VERSION 300
#define CL_USE_DEPRECATED_OPENCL_1_2_APIS
#include <CL/cl.h>
#include <CL/cl_ext.h>
#include <dlfcn.h>
#include <pthread.h>
#include <stddef.h>

static void *lib;
static pthread_once_t once = PTHREAD_ONCE_INIT;
""")
for name, ret, params in funcs:
    print(f"static {ret} (CL_API_CALL *fwd_{name})({', '.join(params) or 'void'});")
print("""
static void load(void) {
    // The vendor library, from the app's namespace (declared with
    // <uses-native-library android:name="libOpenCL.so"> on Android 12+).
    void *m = dlopen("libOpenCL.so", RTLD_NOW | RTLD_LOCAL);
    if (!m) return;""")
for name, ret, params in funcs:
    print(f"    *(void **)&fwd_{name} = dlsym(m, \"{name}\");")
cond = " || ".join(f"!fwd_{n}" for n, _, _ in funcs)
print(f"""    if ({cond}) {{
        dlclose(m);
        return;
    }}
    lib = m;
}}

int oriel_opencl_loader_available(void) {{
    pthread_once(&once, load);
    return lib != NULL;
}}
""")
for name, ret, params in funcs:
    args = ", ".join(param_name(p) for p in params)
    ret_kw = "" if ret == "void" else "return "
    print(f"CL_API_ENTRY {ret} CL_API_CALL {name}({', '.join(params) or 'void'}) {{\n    {ret_kw}fwd_{name}({args});\n}}\n")
