// Bundles src/main.js into ../runtime.js (with linkedom) and
// ../runtime-native.js (with the native DOM), the scripts the Zig side
// embeds and runs in QuickJS. Run `npm install && npm run build` after
// changing src/ or vendor/.
import { build } from "esbuild";
import { fileURLToPath } from "node:url";

// QuickJS has no atob (HTML entity tables are base64).
const atob = `globalThis.atob ??= (s) => {
  const abc = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  let out = "", buf = 0, bits = 0;
  for (const ch of String(s).replace(/[^A-Za-z0-9+/]/g, "")) {
    buf = (buf << 6) | abc.indexOf(ch); bits += 6;
    if (bits >= 8) { bits -= 8; out += String.fromCharCode((buf >> bits) & 255); }
  }
  return out;
};`;
const options = {
  entryPoints: ["src/main.js"],
  bundle: true,
  format: "iife",
  target: "es2023",
  platform: "neutral",
  mainFields: ["module", "main"],
  legalComments: "inline",
  banner: { js: "// Generated by src/native_ui/js/build.mjs from src/native_ui/js/src and vendor: edit those, then `npm run build`.\n" + atob },
  logLevel: "warning",
};
// runtime.js: the DOM is linkedom ("#dom" in package.json's imports).
await build({ ...options, outfile: "../runtime.js" });
// runtime-native.js: the native DOM (-Dnative_dom, docs/native-dom.md).
const nativeDom = {
  name: "native-dom",
  setup(b) { b.onResolve({ filter: /^#dom$/ }, () => ({ path: fileURLToPath(new URL("src/dom/native-backend.js", import.meta.url)) })); },
};
await build({ ...options, outfile: "../runtime-native.js", plugins: [nativeDom] });
