// Generated by oriel from the Zig API. Do not edit.

export interface Commands {
  greet: { args: { name: string; }; result: string };
  app_info: { args: null; result: { zig: string; mode: string; dev: boolean; os: string; } };
  list_notes: { args: null; result: ({ id: number; text: string; created_at: string; })[] };
  add_note: { args: { text: string; }; result: ({ id: number; text: string; created_at: string; })[] };
  do_not_disturb: { args: null; result: boolean };
  export_notes: { args: null; result: string };
  delete_note: { args: { id: number; }; result: ({ id: number; text: string; created_at: string; })[] };
  log_js_deep_link: { args: { url: string; source: string; }; result: null };
}

export interface Events {
  notes_changed: ({ id: number; text: string; created_at: string; })[];
  do_not_disturb: boolean;
  "deep-link": { url: string };
  "permission-changed": { name: PermissionName; status: PermissionStatus };
}

type Args<K extends keyof Commands> = Commands[K]["args"];

export interface WindowOptions {
  label: string;
  url?: string;
  title?: string;
  width?: number;
  height?: number;
  min_width?: number;
  min_height?: number;
  max_width?: number;
  max_height?: number;
  resizable?: boolean;
  decorations?: boolean;
  fullscreen?: boolean;
  maximized?: boolean;
}

export interface WindowHandle {
  readonly label: string;
  close(): Promise<void>;
  show(): Promise<void>;
  hide(): Promise<void>;
  focus(): Promise<void>;
  setTitle(title: string): Promise<void>;
  setSize(width: number, height: number): Promise<void>;
  maximize(maximized?: boolean): Promise<void>;
  fullscreen(fullscreen?: boolean): Promise<void>;
  emit(event: string, payload?: unknown): Promise<void>;
}

export type PermissionName = "microphone" | "camera" | "screen_capture" | "accessibility" | "location" | "notifications" | "system_audio";
export type PermissionStatus = "granted" | "denied" | "prompt" | "unknown";

export interface PermissionsApi {
  /** Current status; never prompts. Undeclared permissions are "denied". */
  query(name: PermissionName): Promise<PermissionStatus>;
  /** Ask the user if the OS allows it; resolves with the outcome. */
  request(name: PermissionName): Promise<PermissionStatus>;
  /** Open the OS settings page for the permission; false when there is none. */
  openSettings(name: PermissionName): Promise<boolean>;
}

export interface DeepLinkApi {
  current(): Promise<string | null>;
}

export interface WindowApi {
  open(options: WindowOptions): Promise<WindowHandle>;
  current(): WindowHandle;
  get(label: string): Promise<WindowHandle | null>;
  all(): Promise<WindowHandle[]>;
  emitTo(label: string, event: string, payload?: unknown): Promise<void>;
}

declare global {
  interface Window {
    oriel: {
      invoke(cmd: string, args: unknown): Promise<unknown>;
      listen(event: string, callback: (payload: unknown) => void): () => void;
      window: WindowApi;
      deepLink: DeepLinkApi;
      permissions: PermissionsApi;
      openExternal(url: string): Promise<void>;
    };
  }
  const oriel: Window["oriel"];
}

/** Call a Zig command. Rejects with the Zig error name on failure. */
export function invoke<K extends keyof Commands>(
  cmd: K,
  ...args: Args<K> extends null ? [] : [Args<K>]
): Promise<Commands[K]["result"]> {
  return window.oriel.invoke(cmd, args[0] ?? null) as Promise<Commands[K]["result"]>;
}

/** Subscribe to an event emitted from Zig. Returns an unsubscribe function. */
export function listen<K extends keyof Events>(event: K, callback: (payload: Events[K]) => void): () => void {
  return window.oriel.listen(event, callback as (payload: unknown) => void);
}

/** Built-in window management API. */
// Not exported as `window`: that would shadow the global inside this module.
export const orielWindow: WindowApi = (globalThis as any).oriel?.window;
/** Built-in deep link API. */
export const deepLink: DeepLinkApi = (globalThis as any).oriel?.deepLink;
/** Built-in OS permissions API. */
export const permissions: PermissionsApi = (globalThis as any).oriel?.permissions;
/** Global Oriel API object. */
export const oriel: Window["oriel"] = (globalThis as any).oriel;
/** Open a URL in the system's default browser. */
export function openExternal(url: string): Promise<void> {
  return window.oriel.openExternal(url);
}
