// The Android app around the Zig library (zig-out/jniLibs/<abi>/liboriel.so,
// built by `zig build -Dtarget=aarch64-linux-android`; `oriel android build`
// builds every ABI and then this). Generated by `oriel android init`.
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "@@app_id@@"
    compileSdk = 35

    defaultConfig {
        applicationId = "@@app_id@@"
        minSdk = 29
        targetSdk = 35
        versionCode = @@version_code@@
        versionName = "@@version@@"
    }

    signingConfigs {
        // Release signing from the environment (`oriel android build`):
        // ORIEL_ANDROID_KEYSTORE, ORIEL_ANDROID_KEYSTORE_PASSWORD,
        // ORIEL_ANDROID_KEY_ALIAS, ORIEL_ANDROID_KEY_PASSWORD.
        create("release") {
            System.getenv("ORIEL_ANDROID_KEYSTORE")?.let { storeFile = file(it) }
            storePassword = System.getenv("ORIEL_ANDROID_KEYSTORE_PASSWORD")
            keyAlias = System.getenv("ORIEL_ANDROID_KEY_ALIAS")
            keyPassword = System.getenv("ORIEL_ANDROID_KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
            if (System.getenv("ORIEL_ANDROID_KEYSTORE") != null) signingConfig = signingConfigs.getByName("release")
        }
    }

    sourceSets["main"].jniLibs.srcDirs("@@lib_dir@@")

    packaging {
        // Zig strips nothing Gradle should strip again; keep the libraries as built.
        jniLibs.keepDebugSymbols += "**/*.so"
        jniLibs.useLegacyPackaging = false
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation("androidx.webkit:webkit:1.12.1")
}
