//! NSIS script generator for building Windows installers (`setup.exe`).
//!
//! Generates a modern per-user NSIS script with:
//! - No administrative privileges required (installs to `$LOCALAPPDATA\Programs\<name>`)
//! - Start Menu shortcut and uninstaller
//! - HKCU registry registration under `Software\Microsoft\Windows\CurrentVersion\Uninstall\<id>`
//! - Bundled application executable and optional `WebView2Loader.dll`
//! - Automatic detection of the Microsoft Edge WebView2 Evergreen runtime
//!   with bootstrapper download/install prompt if missing.

const std = @import("std");
const metadata = @import("metadata.zig");

pub const NsisOptions = struct {
    name: []const u8,
    version: []const u8,
    publisher: []const u8,
    id: []const u8,
    exe_name: []const u8,
    binary_src: []const u8,
    out_file: []const u8,
    icon_path: ?[]const u8 = null,
    webview2_loader: ?[]const u8 = null,
    homepage: ?[]const u8 = null,
    url_schemes: []const []const u8 = &.{},
};

/// Evergreen WebView2 Runtime bootstrapper download URL (Microsoft official fwlink).
pub const WEBVIEW2_BOOTSTRAPPER_URL = "https://go.microsoft.com/fwlink/p/?LinkId=2124703";

/// Generate the complete NSIS script (.nsi) from application metadata and options.
pub fn generateNsisScript(allocator: std.mem.Allocator, opts: NsisOptions) ![]const u8 {
    try metadata.validateExeName(opts.exe_name);

    // Strip trailing .exe if present in exe_name
    const clean_exe_name = if (std.mem.endsWith(u8, opts.exe_name, ".exe"))
        opts.exe_name[0 .. opts.exe_name.len - 4]
    else
        opts.exe_name;

    const esc_name = try metadata.escapeNsisString(allocator, opts.name);
    defer allocator.free(esc_name);

    const esc_exe_name = try metadata.escapeNsisString(allocator, clean_exe_name);
    defer allocator.free(esc_exe_name);

    const esc_version = try metadata.escapeNsisString(allocator, opts.version);
    defer allocator.free(esc_version);

    const esc_publisher = try metadata.escapeNsisString(allocator, opts.publisher);
    defer allocator.free(esc_publisher);

    const esc_id = try metadata.escapeNsisString(allocator, opts.id);
    defer allocator.free(esc_id);

    const esc_bin_src = try metadata.escapeNsisString(allocator, opts.binary_src);
    defer allocator.free(esc_bin_src);

    const esc_out_file = try metadata.escapeNsisString(allocator, opts.out_file);
    defer allocator.free(esc_out_file);

    var esc_icon: ?[]const u8 = null;
    defer if (esc_icon) |ic| allocator.free(ic);
    if (opts.icon_path) |ic| {
        esc_icon = try metadata.escapeNsisString(allocator, ic);
    }

    var esc_wv2: ?[]const u8 = null;
    defer if (esc_wv2) |w| allocator.free(w);
    if (opts.webview2_loader) |w| {
        esc_wv2 = try metadata.escapeNsisString(allocator, w);
    }

    var esc_homepage: ?[]const u8 = null;
    defer if (esc_homepage) |hp| allocator.free(hp);
    if (opts.homepage) |hp| {
        esc_homepage = try metadata.escapeNsisString(allocator, hp);
    }

    var out: std.Io.Writer.Allocating = .init(allocator);
    defer out.deinit();
    const w = &out.writer;

    try w.writeAll(
        \\; Generated by Oriel packaging tool - DO NOT EDIT MANUALLY
        \\Unicode true
        \\SetCompressor /SOLID zlib
        \\RequestExecutionLevel user
        \\
        \\
    );

    try w.print("!define NAME \"{s}\"\n", .{esc_name});
    try w.print("!define EXE_NAME \"{s}\"\n", .{esc_exe_name});
    try w.print("!define VERSION \"{s}\"\n", .{esc_version});
    try w.print("!define PUBLISHER \"{s}\"\n", .{esc_publisher});
    try w.print("!define APP_ID \"{s}\"\n", .{esc_id});
    try w.print("!define BINARY_SRC \"{s}\"\n", .{esc_bin_src});
    try w.print("!define OUT_FILE \"{s}\"\n", .{esc_out_file});

    if (esc_icon) |ic| {
        try w.print("!define ICON_PATH \"{s}\"\n", .{ic});
    }
    if (esc_wv2) |loader| {
        try w.print("!define WEBVIEW2_LOADER \"{s}\"\n", .{loader});
    }
    if (esc_homepage) |hp| {
        try w.print("!define HOMEPAGE \"{s}\"\n", .{hp});
    }

    try w.writeAll(
        \\
        \\Name "${NAME}"
        \\OutFile "${OUT_FILE}"
        \\InstallDir "$LOCALAPPDATA\Programs\${NAME}"
        \\InstallDirRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_ID}" "InstallLocation"
        \\
        \\!ifdef ICON_PATH
        \\Icon "${ICON_PATH}"
        \\UninstallIcon "${ICON_PATH}"
        \\!endif
        \\
        \\!include "MUI2.nsh"
        \\!include "LogicLib.nsh"
        \\
        \\!define MUI_ABORTWARNING
        \\!ifdef ICON_PATH
        \\!define MUI_ICON "${ICON_PATH}"
        \\!define MUI_UNICON "${ICON_PATH}"
        \\!endif
        \\
        \\!insertmacro MUI_PAGE_DIRECTORY
        \\!insertmacro MUI_PAGE_INSTFILES
        \\
        \\!insertmacro MUI_UNPAGE_CONFIRM
        \\!insertmacro MUI_UNPAGE_INSTFILES
        \\
        \\!insertmacro MUI_LANGUAGE "English"
        \\
        \\; Check for the Microsoft Edge WebView2 Evergreen runtime.
        \\; Checks HKCU and HKLM in both 64-bit and 32-bit registry views.
        \\Function CheckWebView2
        \\  Var /GLOBAL wv2_installed
        \\  StrCpy $wv2_installed "0"
        \\
        \\  ReadRegStr $0 HKCU "Software\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" "pv"
        \\  ${If} $0 != ""
        \\  ${AndIf} $0 != "0.0.0.0"
        \\    StrCpy $wv2_installed "1"
        \\  ${EndIf}
        \\
        \\  ${If} $wv2_installed == "0"
        \\    ReadRegStr $0 HKLM "Software\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" "pv"
        \\    ${If} $0 != ""
        \\    ${AndIf} $0 != "0.0.0.0"
        \\      StrCpy $wv2_installed "1"
        \\    ${EndIf}
        \\  ${EndIf}
        \\
        \\  ${If} $wv2_installed == "0"
        \\    ReadRegStr $0 HKLM "Software\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" "pv"
        \\    ${If} $0 != ""
        \\    ${AndIf} $0 != "0.0.0.0"
        \\      StrCpy $wv2_installed "1"
        \\    ${EndIf}
        \\  ${EndIf}
        \\
        \\  ${If} $wv2_installed == "0"
        \\    ReadRegStr $0 HKCU "Software\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}" "pv"
        \\    ${If} $0 != ""
        \\    ${AndIf} $0 != "0.0.0.0"
        \\      StrCpy $wv2_installed "1"
        \\    ${EndIf}
        \\  ${EndIf}
        \\
        \\  ${If} $wv2_installed == "0"
        \\    MessageBox MB_YESNO|MB_ICONEXCLAMATION "Microsoft Edge WebView2 Runtime is required to run ${NAME}.$\n$\nWould you like to download and install it now?" /SD IDNO IDYES install_wv2 IDNO skip_wv2
        \\    install_wv2:
        \\      DetailPrint "Downloading WebView2 Runtime bootstrapper..."
        \\      nsExec::Exec `powershell -NoProfile -ExecutionPolicy Bypass -Command "$$ProgressPreference = 'SilentlyContinue'; [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; (New-Object System.Net.WebClient).DownloadFile('https://go.microsoft.com/fwlink/p/?LinkId=2124703', '$TEMP\MicrosoftEdgeWebview2Setup.exe')"`
        \\      Pop $0
        \\      ${If} $0 == 0
        \\        DetailPrint "Installing WebView2 Runtime..."
        \\        ExecWait '"$TEMP\MicrosoftEdgeWebview2Setup.exe" /silent /install' $1
        \\        Delete "$TEMP\MicrosoftEdgeWebview2Setup.exe"
        \\      ${Else}
        \\        ExecShell "open" "https://go.microsoft.com/fwlink/p/?LinkId=2124703"
        \\      ${EndIf}
        \\      Goto done_wv2
        \\    skip_wv2:
        \\      MessageBox MB_ICONINFORMATION "Please install Microsoft Edge WebView2 Runtime manually before running ${NAME}:$\nhttps://go.microsoft.com/fwlink/p/?LinkId=2124703"
        \\    done_wv2:
        \\  ${EndIf}
        \\FunctionEnd
        \\
        \\Section "Install"
        \\  Call CheckWebView2
        \\
        \\  SetOutPath "$INSTDIR"
        \\  File "/oname=${EXE_NAME}.exe" "${BINARY_SRC}"
        \\  !ifdef WEBVIEW2_LOADER
        \\  File "/oname=WebView2Loader.dll" "${WEBVIEW2_LOADER}"
        \\  !endif
        \\
        \\  ; Generate uninstaller
        \\  WriteUninstaller "$INSTDIR\Uninstall.exe"
        \\
        \\  ; Start Menu Shortcuts
        \\  CreateDirectory "$SMPROGRAMS\${NAME}"
        \\  CreateShortcut "$SMPROGRAMS\${NAME}\${NAME}.lnk" "$INSTDIR\${EXE_NAME}.exe" "" "$INSTDIR\${EXE_NAME}.exe" 0
        \\  CreateShortcut "$SMPROGRAMS\${NAME}\Uninstall ${NAME}.lnk" "$INSTDIR\Uninstall.exe" "" "$INSTDIR\Uninstall.exe" 0
        \\
        \\  ; Add/Remove Programs registry entry under HKCU
        \\  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_ID}" "DisplayName" "${NAME}"
        \\  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_ID}" "DisplayVersion" "${VERSION}"
        \\  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_ID}" "Publisher" "${PUBLISHER}"
        \\  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_ID}" "UninstallString" "$\"$INSTDIR\Uninstall.exe$\""
        \\  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_ID}" "QuietUninstallString" "$\"$INSTDIR\Uninstall.exe$\" /S"
        \\  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_ID}" "DisplayIcon" "$\"$INSTDIR\${EXE_NAME}.exe$\""
        \\  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_ID}" "InstallLocation" "$INSTDIR"
        \\  !ifdef HOMEPAGE
        \\  WriteRegStr HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_ID}" "URLInfoAbout" "${HOMEPAGE}"
        \\  !endif
        \\
    );

    for (opts.url_schemes) |s| {
        const esc_s = try metadata.escapeNsisString(allocator, s);
        defer allocator.free(esc_s);
        try w.print("  ; URL Protocol handler for {s}\n", .{esc_s});
        try w.print("  WriteRegStr HKCU \"Software\\Classes\\{s}\" \"\" \"URL:${{NAME}}\"\n", .{esc_s});
        try w.print("  WriteRegStr HKCU \"Software\\Classes\\{s}\" \"URL Protocol\" \"\"\n", .{esc_s});
        try w.print("  WriteRegStr HKCU \"Software\\Classes\\{s}\\shell\\open\\command\" \"\" \"$\\\"$INSTDIR\\${{EXE_NAME}}.exe$\\\" $\\\"%1$\\\"\"\n", .{esc_s});
    }

    try w.writeAll(
        \\SectionEnd
        \\
        \\Section "Uninstall"
        \\  Delete "$INSTDIR\${EXE_NAME}.exe"
        \\  !ifdef WEBVIEW2_LOADER
        \\  Delete "$INSTDIR\WebView2Loader.dll"
        \\  !endif
        \\  Delete "$INSTDIR\Uninstall.exe"
        \\
        \\  Delete "$SMPROGRAMS\${NAME}\${NAME}.lnk"
        \\  Delete "$SMPROGRAMS\${NAME}\Uninstall ${NAME}.lnk"
        \\  RMDir "$SMPROGRAMS\${NAME}"
        \\
        \\  DeleteRegKey HKCU "Software\Microsoft\Windows\CurrentVersion\Uninstall\${APP_ID}"
        \\
    );

    for (opts.url_schemes) |s| {
        const esc_s = try metadata.escapeNsisString(allocator, s);
        defer allocator.free(esc_s);
        try w.print("  DeleteRegKey HKCU \"Software\\Classes\\{s}\"\n", .{esc_s});
    }

    try w.writeAll(
        \\  RMDir "$INSTDIR"
        \\SectionEnd
        \\
    );

    return try allocator.dupe(u8, out.written());
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

test {
    std.testing.refAllDecls(@This());
}

test "generateNsisScript produces valid script with all options and escaping" {
    const testing = std.testing;
    const allocator = testing.allocator;

    const opts = NsisOptions{
        .name = "Oriel \"React\" Notes $1",
        .version = "0.2.0",
        .publisher = "Oriel \"Team\" $Org",
        .id = "dev.oriel.ReactNotes",
        .exe_name = "oriel-react-notes",
        .binary_src = "/path/to/bin with spaces/notes.exe",
        .out_file = "/path/to/out/setup.exe",
        .icon_path = "/path/to/icon.ico",
        .webview2_loader = "/path/to/WebView2Loader.dll",
        .homepage = "https://oriel.dev",
    };

    const script = try generateNsisScript(allocator, opts);
    defer allocator.free(script);

    // Verify escaped defines
    try testing.expect(std.mem.indexOf(u8, script, "!define NAME \"Oriel $\\\"React$\\\" Notes $$1\"") != null);
    try testing.expect(std.mem.indexOf(u8, script, "!define PUBLISHER \"Oriel $\\\"Team$\\\" $$Org\"") != null);
    try testing.expect(std.mem.indexOf(u8, script, "!define EXE_NAME \"oriel-react-notes\"") != null);
    try testing.expect(std.mem.indexOf(u8, script, "!define VERSION \"0.2.0\"") != null);
    try testing.expect(std.mem.indexOf(u8, script, "!define APP_ID \"dev.oriel.ReactNotes\"") != null);
    try testing.expect(std.mem.indexOf(u8, script, "!define ICON_PATH \"/path/to/icon.ico\"") != null);
    try testing.expect(std.mem.indexOf(u8, script, "!define WEBVIEW2_LOADER \"/path/to/WebView2Loader.dll\"") != null);
    try testing.expect(std.mem.indexOf(u8, script, "!define HOMEPAGE \"https://oriel.dev\"") != null);

    // Verify per-user and MUI2 settings
    try testing.expect(std.mem.indexOf(u8, script, "RequestExecutionLevel user") != null);
    try testing.expect(std.mem.indexOf(u8, script, "InstallDir \"$LOCALAPPDATA\\Programs\\${NAME}\"") != null);
    try testing.expect(std.mem.indexOf(u8, script, "!include \"MUI2.nsh\"") != null);

    // Verify registry uninstall key
    try testing.expect(std.mem.indexOf(u8, script, "WriteRegStr HKCU \"Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_ID}\"") != null);
    try testing.expect(std.mem.indexOf(u8, script, "DeleteRegKey HKCU \"Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\${APP_ID}\"") != null);

    // Verify WebView2 detection
    try testing.expect(std.mem.indexOf(u8, script, "Function CheckWebView2") != null);
    try testing.expect(std.mem.indexOf(u8, script, "{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}") != null);
    try testing.expect(std.mem.indexOf(u8, script, WEBVIEW2_BOOTSTRAPPER_URL) != null);
}

test "generateNsisScript strips .exe suffix from exe_name" {
    const testing = std.testing;
    const allocator = testing.allocator;

    const opts = NsisOptions{
        .name = "My App",
        .version = "1.0.0",
        .publisher = "Publisher",
        .id = "com.example.App",
        .exe_name = "myapp.exe",
        .binary_src = "bin/myapp.exe",
        .out_file = "dist/setup.exe",
    };

    const script = try generateNsisScript(allocator, opts);
    defer allocator.free(script);

    try testing.expect(std.mem.indexOf(u8, script, "!define EXE_NAME \"myapp\"") != null);
    try testing.expect(std.mem.indexOf(u8, script, "!define EXE_NAME \"myapp.exe\"") == null);
}

test "generateNsisScript with url_schemes" {
    const testing = std.testing;
    const allocator = testing.allocator;

    const opts = NsisOptions{
        .name = "My App",
        .version = "1.0.0",
        .publisher = "Publisher",
        .id = "com.example.App",
        .exe_name = "myapp",
        .binary_src = "bin/myapp.exe",
        .out_file = "dist/setup.exe",
        .url_schemes = &.{ "myapp", "custom-scheme" },
    };

    const script = try generateNsisScript(allocator, opts);
    defer allocator.free(script);

    // Verify HKCU registration
    try testing.expect(std.mem.indexOf(u8, script, "WriteRegStr HKCU \"Software\\Classes\\myapp\" \"\" \"URL:${NAME}\"") != null);
    try testing.expect(std.mem.indexOf(u8, script, "WriteRegStr HKCU \"Software\\Classes\\myapp\" \"URL Protocol\" \"\"") != null);
    try testing.expect(std.mem.indexOf(u8, script, "WriteRegStr HKCU \"Software\\Classes\\myapp\\shell\\open\\command\" \"\" \"$\\\"$INSTDIR\\${EXE_NAME}.exe$\\\" $\\\"%1$\\\"\"") != null);

    try testing.expect(std.mem.indexOf(u8, script, "WriteRegStr HKCU \"Software\\Classes\\custom-scheme\" \"\" \"URL:${NAME}\"") != null);

    // Verify uninstallation deletion
    try testing.expect(std.mem.indexOf(u8, script, "DeleteRegKey HKCU \"Software\\Classes\\myapp\"") != null);
    try testing.expect(std.mem.indexOf(u8, script, "DeleteRegKey HKCU \"Software\\Classes\\custom-scheme\"") != null);
}

