// The Android app around the Zig library (zig-out/jniLibs/<abi>/liboriel.so,
// built by `zig build -Dtarget=aarch64-linux-android`; `oriel android build`
// builds every ABI and then this). Generated by `oriel android init`.
plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "dev.oriel.Breakout"
    compileSdk = 35

    defaultConfig {
        applicationId = "dev.oriel.Breakout"
        minSdk = 29
        targetSdk = 35
        versionCode = 100
        versionName = "0.1.0"
    }

    signingConfigs {
        // Release signing from the environment (`oriel android build`):
        // ORIEL_ANDROID_KEYSTORE, ORIEL_ANDROID_KEYSTORE_PASSWORD,
        // ORIEL_ANDROID_KEY_ALIAS, ORIEL_ANDROID_KEY_PASSWORD.
        create("release") {
            System.getenv("ORIEL_ANDROID_KEYSTORE")?.let { storeFile = file(it) }
            storePassword = System.getenv("ORIEL_ANDROID_KEYSTORE_PASSWORD")
            keyAlias = System.getenv("ORIEL_ANDROID_KEY_ALIAS")
            keyPassword = System.getenv("ORIEL_ANDROID_KEY_PASSWORD")
        }
    }

    buildTypes {
        release {
            // R8 shrinks the Kotlin runtime and androidx (2.9 -> 0.13 MB of
            // dex); proguard-rules.pro keeps what the native code calls by name.
            isMinifyEnabled = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            if (System.getenv("ORIEL_ANDROID_KEYSTORE") != null) signingConfig = signingConfigs.getByName("release")
        }
    }

    sourceSets["main"].jniLibs.srcDirs("../../zig-out/jniLibs")

    packaging {
        // Release libraries come stripped from Zig, Debug ones keep their
        // symbols: either way Gradle keeps the libraries as built.
        jniLibs.keepDebugSymbols += "**/*.so"
        // Extracted on install: liboriel_exec.so (the app's own executable,
        // for helper processes) must be a file Android lets the app run.
        jniLibs.useLegacyPackaging = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    implementation("androidx.webkit:webkit:1.12.1")
}
