//! Build tool: copy a built frontend directory (e.g. Vite's `dist/`) into the
//! build cache and generate `assets.zig`, which `@embedFile`s every file:
//!
//!     pub const files: []const oriel.App.Asset = &.{ ... };
//!
//! Usage: embed_assets <src_dir> <out_dir>

const std = @import("std");
const builtin = @import("builtin");
const Dir = std.Io.Dir;
const csp = @import("csp");

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const gpa = init.gpa;
    // Portable argv (WTF-16 on Windows, so not `args.vector`).
    const argv = try init.minimal.args.toSlice(init.arena.allocator());
    if (argv.len != 3) {
        std.debug.print("usage: embed_assets <src_dir> <out_dir>\n", .{});
        std.process.exit(2);
    }
    const src_path = argv[1];
    const out_path = argv[2];

    var src = Dir.cwd().openDir(io, src_path, .{ .iterate = true }) catch |err| {
        std.debug.print("embed_assets: cannot open {s}: {s} (was the frontend built?)\n", .{ src_path, @errorName(err) });
        std.process.exit(1);
    };
    defer src.close(io);
    try Dir.cwd().createDirPath(io, out_path);
    var out = try Dir.cwd().openDir(io, out_path, .{});
    defer out.close(io);

    var paths: std.ArrayList([]const u8) = .empty;
    defer {
        for (paths.items) |p| gpa.free(p);
        paths.deinit(gpa);
    }
    var walker = try src.walk(gpa);
    defer walker.deinit();
    while (try walker.next(io)) |entry| {
        if (entry.kind != .file) continue;
        // Asset keys and @embedFile paths use '/'; the walker returns the
        // native separator ('\\' on Windows).
        const rel = try gpa.dupe(u8, entry.path);
        errdefer gpa.free(rel);
        if (builtin.os.tag == .windows) std.mem.replaceScalar(u8, rel, '\\', '/');
        if (std.mem.indexOfAny(u8, rel, "\"\\\n") != null) return error.UnsupportedFileName;
        try paths.append(gpa, rel);
    }
    std.mem.sort([]const u8, paths.items, {}, lessThan);

    var source: std.Io.Writer.Allocating = .init(gpa);
    defer source.deinit();
    const w = &source.writer;
    try w.writeAll(
        \\// Generated by oriel's embed_assets. Do not edit.
        \\const oriel = @import("oriel");
        \\
        \\pub const files: []const oriel.App.Asset = &.{
        \\
    );
    for (paths.items) |path| {
        const dest = try std.fmt.allocPrint(gpa, "files/{s}", .{path});
        defer gpa.free(dest);
        if (std.fs.path.dirname(dest)) |dir| try out.createDirPath(io, dir);
        try src.copyFile(path, out, dest, io, .{});
        try w.print("    .{{ .path = \"{s}\", .data = @embedFile(\"{s}\"), .mime = \"{s}\"", .{ path, dest, mimeType(path) });
        // HTML: the CSP hashes of its inline scripts and style blocks.
        if (std.ascii.eqlIgnoreCase(std.fs.path.extension(path), ".html") or std.ascii.eqlIgnoreCase(std.fs.path.extension(path), ".htm")) {
            const html = try src.readFileAlloc(io, path, gpa, .limited(64 * 1024 * 1024));
            defer gpa.free(html);
            const hashes = try csp.inlineHashes(gpa, html);
            defer hashes.deinit(gpa);
            if (hashes.scripts.len > 0) try w.print(", .script_hashes = \"{s}\"", .{hashes.scripts});
            if (hashes.styles.len > 0) try w.print(", .style_hashes = \"{s}\"", .{hashes.styles});
        }
        try w.writeAll(" },\n");
    }
    try w.writeAll("};\n");
    try out.writeFile(io, .{ .sub_path = "assets.zig", .data = source.written() });
}

fn lessThan(_: void, a: []const u8, b: []const u8) bool {
    return std.mem.lessThan(u8, a, b);
}

fn mimeType(path: []const u8) []const u8 {
    const ext = std.fs.path.extension(path);
    const table = [_]struct { []const u8, []const u8 }{
        .{ ".html", "text/html" },
        .{ ".js", "text/javascript" },
        .{ ".mjs", "text/javascript" },
        .{ ".css", "text/css" },
        .{ ".json", "application/json" },
        .{ ".map", "application/json" },
        .{ ".svg", "image/svg+xml" },
        .{ ".png", "image/png" },
        .{ ".jpg", "image/jpeg" },
        .{ ".jpeg", "image/jpeg" },
        .{ ".gif", "image/gif" },
        .{ ".webp", "image/webp" },
        .{ ".ico", "image/x-icon" },
        .{ ".woff", "font/woff" },
        .{ ".woff2", "font/woff2" },
        .{ ".ttf", "font/ttf" },
        .{ ".wasm", "application/wasm" },
        .{ ".txt", "text/plain" },
    };
    for (table) |entry| {
        if (std.ascii.eqlIgnoreCase(ext, entry[0])) return entry[1];
    }
    return "application/octet-stream";
}
